### ISSUE TITLE
Generates warnings with webpack

### ISSUE THREAD

**Issue by jescalan** [gulp-community/gulp-wrap-umd#10]
So I do realize that this is webpack's fault, but at the same time it's a very common option these days and I feel like it would be a nice benefit if the wrapper worked seamlessly when integrated into a webpack pipeline.

When you try to load a plugin with a umd wrapper into webpack it generates the warning: `require function is used in a way in which dependencies cannot be statically extracted`. There is [a plugin](https://github.com/resin-io/umd-require-webpack-plugin) that briefly explains why and fixes this.

**Comment by phated** [comment]
I recommend using the plugin.  This is a proper UMD and webpack is at fault in this incompatibility.
