### ISSUE TITLE
Is the functionality of this gulp-plugin available as a standalone module?

### ISSUE THREAD

**Issue by 5310** [gulp-community/gulp-wrap-umd#6]
Apologize for this non-bug issue, but I had a question.

gulp-wrap-umd is the only UMD wrapper I could find that supports namespaced global alias and and allows extended aliased externalization of dependencies.

I would like to use the functionality in a project where I don't use gulp, and was wondering if the functionality of this plugin was available as a standalone module, with or without command line api, which I will could with in my workflow.

If no such version is planned, would you happen to know any standalone module that already does this?

**Comment by phated** [comment]
I've never explored making this a standalone module.  Most of the template options came from my work with grunt-jade.  You can use `require('gulp-jade/template')` to get the compiled lodash template that you just need to pass the context to.  I guess you would miss out on normalization of deps though.

**Comment by 5310** [comment]
I definitely will look into just using the templates into my workflow. Maybe I can also borrow the dependency normalization parts too? I'll try.

Thank you for the answer.
